---
title: "Optimisation des Chaînes d'Approvisionnement Pharmaceutiques en Temps de Crise : Le Cas de VACZIN"
author: Nizar OUNIR
output: html_notebook
---
```{r Code Simulation}
# MANUFACTURING PROCESS SIMULATION: VACZIN

# Load Libraries
library(simmer)
library(simmer.bricks)
library(simmer.plot)

# Definition des paramêtres nécessaires à la Simulation
set.seed(3141)  

SimTime <- 15 * 480   # Simulation Duration (mins)
DD <- 10              # Daily Demand (units/day)
RT <- 3 * 480         # Replenishment Time (mins)
ROP <- 45             # units
ROQ <- 25             # units
NumVaccins <- 50      # units
NumSeringues <- 50    # units
MTTR <- 60            # Mean Time To Repair (mins)
MTBF <- 7 * 480       # Mean Time Between Failures (mins)
Rework <- 0.02        # Products needing rework

# Inter arrival times (Customers, Work Oders)
CustArr <- function() rexp(1, DD) * 480   # mins
Forecast <- function() {50}                # mins

# Définir les Ressources et Trajectoires
VACZIN <- simmer()

# Ajout des ressources
VACZIN %>%
  add_global("Inventaire Vaccins", NumVaccins) %>%
  add_global("Inventaire Seringues", NumSeringues) %>%
  add_resource("Vaccin", NumVaccins) %>%
  add_resource("Seringue", NumSeringues) %>%
  add_resource("Lot Fini", 10) #on commence à 10 histoire d'avoir du stock au tout début pour les premiers clients

# Ajout des machines
machines <- c("M1 : Dissolution", "M2 : Filtration Clarifiante", "M3 : Repartition", "M4 : Setrilisation Terminale", "M5 : Sérialisation ")
for (machine in machines) {
  VACZIN %>% add_resource(machine, 1)
}

# Trajectoire Clients
t_Client <- trajectory() %>%
  seize("Lot Fini", 1) %>%
  timeout(5) %>%
  release("Lot Fini", 1) %>%
  set_capacity("Lot Fini", -1, mod = "+")  # Reduit le Stock de Lot Fini de 1

# Trajectoire des Work Orders
t_Ligne_de_Prod <- trajectory() %>%
  seize("Vaccin", 1) %>%
  visit("M1 : Dissolution", 40, 1) %>%
  visit("M2 : Filtration Clarifiante", 40, 1) %>%
  release("Vaccin", 1) %>%
  seize("Seringue", 1) %>%
  visit("M3 : Repartition", 40, 1) %>%
  visit("M4 : Setrilisation Terminale", 40, 1) %>%
  rollback(6, check = function() runif(1) <= Rework) %>%
  set_capacity("Vaccin", -1, mod = "+") %>%
  set_global("Inventaire Vaccins", -1, mod = "+") %>%
  set_capacity("Seringue", -1, mod = "+") %>%
  set_global("Inventaire Seringues", -1, mod = "+") %>%
  set_capacity("Lot Fini", 1, mod = "+") %>%
  release("Seringue", 1)  # Libérer les ressources acquises

plot(t_Ligne_de_Prod)

# Trajectoire pour le controle de stock
t_Restock_Vaccin <- trajectory() %>%
  branch(function() get_global(VACZIN, "Inventaire Vaccins") <= ROP,
         continue = TRUE,
         trajectory() %>%
           set_global("Inventaire Vaccins", ROQ, mod = "+") %>%
           timeout(RT) %>%
           set_capacity("Vaccin", ROQ, mod = "+")
  ) %>%
  timeout(0)

# Trajectoire pour la panne de la M2: filtration
t_Panne <- trajectory() %>%
  visit("M2 : Filtration Clarifiante", MTTR, 1)

# Ajout des générateurs
VACZIN %>%
  add_generator("Clients", t_Client, CustArr) %>%
  add_generator("Carnet de Commande", t_Ligne_de_Prod, Forecast) %>%
  add_generator("Scan Vaccin", t_Restock_Vaccin, function() {30}) %>%
  add_generator("Pannes", t_Panne,
                function() {rexp(1, 1/MTBF)},
                priority = 1)  

# Lancer La Simulation
VACZIN %>% run(until = SimTime)

# Stocker les Résultats
Arrivals <- get_mon_arrivals(VACZIN)
Ressources <- get_mon_resources(VACZIN)
Journal_de_Bord <- get_mon_attributes(VACZIN)

head(Arrivals)
head(Ressources)
head(Journal_de_Bord)

```

# 1. Introduction\
## 1.1 Contexte et justification\
## 1.2 Objectifs et questions de recherche\
## 1.3 Méthodologie de modélisation et de simulation\

# 2. Revue de la littérature\
## 2.1 Modélisation des processus pharmaceutiques\
## 2.2 Simulation appliquée à l'industrie pharmaceutique\
## 2.3 Cadre réglementaire de la fabrication de vaccins\

# 3. Méthodologie de simulation\
##   3.1 Choix du modèle de simulation\
##   3.2 Outils et techniques utilisés\
##   3.3 Collecte et traitement des données épidémiologiques et industrielles\

# 4. Modèle de simulation des processus de fabrication de vaccins\
##   4.1 Architecture et composants du modèle\
##   4.2 Paramètres du modèle et justification\
##   4.3 Intégration des aspects galéniques et épidémiologiques\

#5. Application des Bonnes Pratiques de Fabrication (BPF)\
##   5.1 Principes et normes des BPF\
##   5.2 Adaptation des BPF à la modélisation des processus de fabrication de vaccins\
##   5.3 Gestion des risques et assurance qualité\

# 6. Considérations réglementaires dans la fabrication de vaccins
##   6.1 Cadre réglementaire européen et international
##   6.2 Impact des réglementations sur les processus de production
##   6.3 Conformité aux exigences réglementaires et aux standards de qualité

# 7. Approche épidémiologique et stratégique
##   7.1 Analyse de la prévalence des maladies ciblées par les vaccins
##   7.2 Planification stratégique de la production en fonction des besoins de santé publique
##   7.3 Évaluation de l'efficacité des programmes de vaccination

# 8. Résultats de la simulation et interprétation
##   8.1 Présentation des résultats de la simulation
##   8.2 Analyse et interprétation des données obtenues
##   8.3 Discussion des implications pour l'industrie pharmaceutique et la santé publique

# 9. Conclusion et recommandations
##   9.1 Synthèse des conclusions de l'étude
##  9.2 Recommandations pour les décideurs et les acteurs de l'industrie pharmaceutique
##   9.3 Perspectives futures de recherche et de développement

# 10. Annexes
##    10.1 Données supplémentaires et détails techniques
##    10.2 Diagrammes, tableaux et figures complémentaires
##    10.3 Documentation méthodologique et informatique du modèle de simulation

# 11. Références